[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[redirects]]
  from = "/trip-to-elora/index.html"
  to = "/journal/trip-to-elora/index.html"
  status = 301

[[redirects]]
from = "/*"
to = "/404/index.html"
status = 404